### ISSUE TITLE
requires-python set incorrectly

### ISSUE THREAD

**Issue by dstansby** [UCL-ARC/python-tooling#298] opened 2024-02-06 10:45 UTC
### Describe the Bug

When a maximum python version is specified when running the cookiecutter, `requires-python` in `pyproject.toml` is set incorrectly.

### To Reproduce

Run the cookiecutter and select min python = 3.11, max python = 3.11.

### Expected Behaviour

In `pyproject.toml`, `requires-python = "==3.11"`.

### Actual Behaviour

In `pyproject.toml`, `requires-python = ">=3.11"`.

### Additional Context

```markdown
- Cookiecutter version:
- Operating system:
- Python version:
```

**Comment by paddyroddy** [comment] 2024-02-06 14:46
Should probably be changed to something like `">={{cookiecutter.min_python_version}}; <={{cookiecutter.max_python_version}}"`. Obviously `>=3.11; <=3.11` is a bit silly, but I don't think this is a big issue.

**Comment by samcunliffe** [comment] 2024-02-06 15:52
(Assuming my code actually works) what do we think of this relatively elaborate if statement version...
```
{%- if cookiecutter.max_version == cookiecutter.min_version -%}
requires-python = "=={{cookiecutter.max_python_version}}"
{%- else -%}
requires-python = ">={{cookiecutter.min_python_version}};<={{cookiecutter.max_python_version}}"
{%- endif -%}
```

**Comment by paddyroddy** [comment] 2024-02-06 16:40
I've looked into this, and realise that what we currently have is correct. So will close this issue.

For reference, to "fix" this we could do something like
```toml
requires-python = {% if cookiecutter.min_python_version == cookiecutter.max_python_version %}"=={{cookiecutter.max_python_version}}"{% else %}">={{cookiecutter.min_python_version}}, <={{cookiecutter.max_python_version}}"{% endif %}
```

The problem is, when you have `requires-python = "==3.12"`, you get this error when trying to install it
```
ERROR: Package 'python-template' requires a different Python: 3.12.1 not in '==3.12'
```

When you have `requires-python = ">=3.9, <=3.12"` you get
```
ERROR: Package 'python-template' requires a different Python: 3.12.1 not in '<=3.12,>=3.9'
```

If you look at the [packaging docs](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#python-requires) it says
> This lets you declare the minimum version of Python that you support
>> Think twice before applying an upper bound like requires-python = "<= 3.10" here. [This blog post](https://iscinumpy.dev/post/bound-version-constraints/#pinning-the-python-version-is-special) contains some information regarding possible problems.

**Closed as not planned by paddyroddy** 2024-02-06 16:40 UTC
Labels: bug

**Comment by dstansby** [comment] 2024-02-06 16:58
I think the right fix is `requires-python=~=3.12`? This should allow any version that's compatible with 3.12, which includes any bugfix releases.

**Comment by paddyroddy** [comment] 2024-02-06 17:04
I don't think we should go against the PPA

**Comment by dstansby** [comment] 2024-02-06 17:18
Isn't that just a blog post, not official advice from the PPA? Anyway, I had a read and I buy the argument that:

> “Scrolling back” through older releases to find the newest version that does not restrict the version of Python being used is exactly the wrong behavior for an upper cap, and that is what the purpose of this field is

So instead can we implement a check on the Python version in `__init__.py` in the package, and raise an error if it's not an allowed version of Python?

**Comment by paddyroddy** [comment] 2024-02-06 17:42
> Isn't that just a blog post, not official advice from the PPA? Anyway, I had a read and I buy the argument that:

>> Welcome to the Python Packaging User Guide, a collection of tutorials and references to help you distribute and install Python packages with modern tools.
>> 
>> This guide is maintained on [GitHub](https://github.com/pypa/packaging.python.org) by the [Python Packaging Authority](https://www.pypa.io/en/latest/). We happily accept [contributions and feedback](https://packaging.python.org/en/latest/contribute/). 😊

> So instead can we implement a check on the Python version in `__init__.py` in the package, and raise an error if it's not an allowed version of Python?

That could be a better idea.
